doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        # server_version: '8.0'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Template:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Infrastructure/Template/Persistence/Doctrine/Mapping'
                type: xml
                prefix: 'App\Domain\Template\Entity'
                alias: App
            App\Verification:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Infrastructure/Verification/Persistence/Doctrine/Mapping/'
                type: xml
                prefix: 'App\Domain\Verification\Entity'
                alias: App
            App\Verification\Subject:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Infrastructure/Verification/Persistence/Doctrine/Mapping/Subject/'
                type: xml
                prefix: 'App\Domain\Verification\Entity\Subject'
                alias: App
            App\Notification:
                dir: '%kernel.project_dir%/src/Infrastructure/Notification/Persistence/Doctrine/Mapping/'
                type: xml
                prefix: 'App\Domain\Notification\Entity'


when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
