nelmio_api_doc:
    documentation:
        info:
            title: Verification service
            version: 1.0.0
    areas:
        path_patterns:
            - ^/templates
            - ^/verifications
